### ISSUE TITLE
Simple test fails with 'TypeError: You may only yield a function...'

### ISSUE THREAD

**Issue by p14n** [blakeembrey/co-mocha#16]
I'm hitting a problem in my tests and I can get the same thing with the simplest of tests.  Using the file simple.js containing:
```javascript
it('should do something', function* () {
  yield;
});
```
When I run:
```
node node_modules/mocha/bin/mocha --require co-mocha simple.js
```
I get 
```
  1)  should do something:
     TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed: "undefined"
      at next (/Users/p14n/dev/tools/moch/node_modules/co-mocha/node_modules/co/index.js:100:25)
```
co-mocha 1.1.0
mocha 2.0.1
node 1.6.4

I can't see why that wouldn't work?

Cheers

**Comment by blakeembrey** [comment]
@p14n Looks like someone has asked about it a while ago on the `co` repo (https://github.com/tj/co/issues/119). Does that help you?

**Comment by p14n** [comment]
Yes thanks (it's not expected to work).  Returning an array there works fine.
