### ISSUE TITLE
Add support in browser.

### ISSUE THREAD

**Issue by lygstate** [blakeembrey/co-mocha#18]

**Comment by blakeembrey** [comment]
Released with `1.1.1`. Let me know if there's a browser use-case not handled though. This would have previously worked already with a Browserified build, but I'm now including it for you.

**Comment by lygstate** [comment]
@blakeembrey  Thanks a lot. co dependence is out data, maybe it's a good idea to upgrade it:)

**Comment by blakeembrey** [comment]
@lygstate It should be fine. https://github.com/blakeembrey/co-mocha/blob/master/package.json#L62 will go from `4.0` to `< 5.0`.

**Comment by lygstate** [comment]
Thanks @blakeembrey , Could you please upload the co-mocha package into bower.io site?

**Comment by blakeembrey** [comment]
Sure, I was planning that actually but forgot to register it. I'll register it now.
