### ISSUE TITLE
A failing test in a co context is not propagated to mocha

### ISSUE THREAD

**Issue by TMiguelT** [blakeembrey/co-mocha#23]
I've made an example repository here to demonstrate the issue: https://github.com/TMiguelT/co-mocha-test

To run it, use:
```bash
git clone https://github.com/TMiguelT/co-mocha-test\
&& cd co-mocha-test\
&& npm install\
&& npm test
```

The code in question is this:
```javascript
require('co-mocha');
require('assert');

describe("describe", () => {
  it("it", function *(done){
      assert(1 + 1 == 2);
      done();
  });
});
```

Basically, this causes a timeout error because `done()` is never called because the `assert()` fails. However ideally co-mocha would catch this error and pass it back to mocha to indicate a failed test.

**Comment by blakeembrey** [comment]
You can't use promises and callbacks together anyway, so there's no way this can work.

**Comment by TMiguelT** [comment]
Yep you're correct. If anyone else reads this in the future, if you just leave out the `done` argument to `it()`, mocha will assume the function returns a promise, so it'll all work correctly:

```javascript
require('co-mocha');
const assert = require('assert');

describe("describe", () => {
  it("it", function *(){
      assert(1 + 1 == 2);
  });
});
```
