### ISSUE TITLE
It seems not working on new version

### ISSUE THREAD

**Issue by magicdawn** [blakeembrey/co-mocha#24]
node@v6.5.0
npm@3.10.3
"co-mocha": "^1.1.3",
"mocha": "^3.0.2",

``` js
describe('Push', function() {
  it('hello', function*() {
    throw new Error('xxx');
  });
});
```

$ mocha test/push.js

  Push
    ✓ hello

  1 passing (7ms)

**Comment by blakeembrey** [comment]
@magicdawn Unless it's been required, it's not part of the project. You need to require it at some point, either using the CLI or within the test module. E.g. `mocha -r co-mocha test/push.js`.

**Comment by magicdawn** [comment]
@blakeembrey yeah. I forget to paste my `mocha.opts` file, I required co-mocha in there

mocha.opts
```
--require should
--require co-mocha
-R spec
```

It works well in old versions I remembered. And after a upgrade mocha & co-mocha, this get not working.

**Comment by solsenfinovertech** [comment]
I too am having this issue of thrown Errors still passing the tests.

I used to just require the module:
```
require('co-mocha')
```

but I noticed the docs say:
```
var mocha = require('mocha')
var coMocha = require('co-mocha')
coMocha(mocha)
```

Was I including it wrong the whole time?!

**Comment by blakeembrey** [comment]
@solsenfinovertech No, that's correct - see the docs here: https://github.com/blakeembrey/co-mocha#node. That's only if you need to manually monkey patch a different instance than what was picked up automatically. Did it work after the change? Perhaps the `mocha` resolution has changed in some way.

**Comment by magicdawn** [comment]
It's still not working, I create a fresh  project here https://github.com/magicdawn/co-mocha-test

**Comment by solsenfinovertech** [comment]
I discovered that the problem was my npm script:

`istanbul cover node_modules/mocha/bin/_mocha -- --reporter=xunit-file api/**/*.spec.js api/**/*.test.js lib/**/*.test.js; istanbul report cobertura --dir shippable/codecoverage/`

The `--reporter` was the culprit -- actually, the test *was* failing, but the console output didn't show it.

Resolved for me thx. 👍

**Comment by blakeembrey** [comment]
@magicdawn The project you shared works for me:

![image](https://cloud.githubusercontent.com/assets/1088987/21193828/a03e07f6-c1fb-11e6-914c-9ee3f5f3d47c.png)

![image](https://cloud.githubusercontent.com/assets/1088987/21193845/ab3e9e54-c1fb-11e6-9fc7-44740ef47fbc.png)

**Comment by magicdawn** [comment]
@blakeembrey 

Yeah, just found it's ok with npm. Previous I use `cnpm` (another npm install tool).
And results a different folder structure in node_modules, I will look into that. Thanks

**Comment by blakeembrey** [comment]
Hmm, that seems odd still. Is it possibly named differently in the node cache? This is all the logic for finding the required `mocha` instance - https://github.com/blakeembrey/co-mocha/blob/9bc0f577789a4a2723f9dedd1b5bf34a080fd506/lib/co-mocha.js#L55.

**Comment by magicdawn** [comment]
@blakeembrey 

![image](https://cloud.githubusercontent.com/assets/4067115/21259858/5d73b776-c3be-11e6-91b0-c6b5b52d6968.png)

the cnpm tool will create a symlink to the real package folder for share common modules

And I tried Yarn, it's also ok
![image](https://cloud.githubusercontent.com/assets/4067115/21259944/c41e1098-c3be-11e6-92e0-ae328a31d844.png)

Any reason for find the mocha instance manually ?
And a idea here:
- specify `mocha` as `co-mocha` 's peerDependency 
- just use `require('mocha')`

**Comment by magicdawn** [comment]
```sh
magicdawn at bogon in ~/projects/co-mocha-test (master●)
$ ll node_modules | grep mocha
lrwxr-xr-x  1 magicdawn  staff    15B 12 16 19:17 co-mocha -> .1.1.3@co-mocha
lrwxr-xr-x  1 magicdawn  staff    12B 12 16 19:17 mocha -> .3.2.0@mocha
```

**Comment by blakeembrey** [comment]
We find it manually because the user might not be using the instance you get back when you use `require` - for example, when using `mocha` globally. I'm not sure if there's any other edge-cases to be aware of.

**Comment by magicdawn** [comment]
What about this: we are finding mocha, so let's find `Mocha`

```js
function findNodeJSMocha () {
  var children = require.cache || {}

  return Object.keys(children)
    .filter(function (child) {
      var val = children[child].exports
      return typeof val === 'function' && val.name === 'Mocha'
    })
    .map(function (child) {
      return children[child].exports
    })
}
```

btw 😂 
![image](https://cloud.githubusercontent.com/assets/4067115/21283492/4204af24-c43e-11e6-9557-b4f5a0157d3d.png)

**Comment by blakeembrey** [comment]
Closed with https://github.com/blakeembrey/co-mocha/pull/27.
